database:
  url = jdbc:mysql://localhost:3306/book_store
  login = root
  password = Alexunder_90
  migration.location = db/migration
  driver = com.mysql.cj.jdbc.Driver
hibernate:
  hbm2ddl.auto.property = update
  dialect.property = org.hibernate.dialect.MySQL8Dialect
  show_sql.property = true
  format_sql.property = true
spring:
  profiles:
    active: "default,dev,stable"

  entity.package.to.scan = com.flashsuppressor.java.lab.entity