info:
  _postman_id: b521d871-3c46-4c8a-9304-892ea694da47
  name: bookStoreApp.publishers
  schema: https://schema.getpostman.com/json/collection/v2.1.0/collection.json
item:
  - name: findPublisherById
    protocolProfileBehavior:
      disableBodyPruning: true
    request:
      method: GET
      header:
        - key: Authorization
          value: >-
            eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBbGV4QGNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYzODY5NzIyMywiZXhwIjoxNjM4NzYyNzU5fQ.4uQv2NHCZldbzpy_7zD2En3CElAEJQ9bz1q0bmZIhlc
          type: text
      body:
        mode: raw
        raw: ''
        options:
          raw:
            language: json
      url:
        raw: http://localhost:8080/publishers/1
        protocol: http
        host:
          - localhost
        port: '8080'
        path:
          - publishers
          - '1'
    response: []
  - name: findAllPublishers
    request:
      method: GET
      header:
        - key: Authorization
          value: >-
            eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBbGV4QGNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYzODY5NzIyMywiZXhwIjoxNjM4NzYyNzU5fQ.4uQv2NHCZldbzpy_7zD2En3CElAEJQ9bz1q0bmZIhlc
          type: text
      url:
        raw: http://localhost:8080/publishers/all
        protocol: http
        host:
          - localhost
        port: '8080'
        path:
          - publishers
          - all
    response: []
  - name: createPublisher
    request:
      method: POST
      header:
        - key: Authorization
          value: >-
            eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBbGV4QGNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYzODY5NzIyMywiZXhwIjoxNjM4NzYyNzU5fQ.4uQv2NHCZldbzpy_7zD2En3CElAEJQ9bz1q0bmZIhlc
          type: text
      body:
        mode: raw
        raw: "{\r\n    \"name\":\"Bee to Bee\"\r\n}"
        options:
          raw:
            language: json
      url:
        raw: http://localhost:8080/publishers/
        protocol: http
        host:
          - localhost
        port: '8080'
        path:
          - publishers
          - ''
    response: []
  - name: createAllPublishers
    request:
      method: POST
      header:
        - key: Authorization
          value: >-
            eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBbGV4QGNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYzODY5NzIyMywiZXhwIjoxNjM4NzYyNzU5fQ.4uQv2NHCZldbzpy_7zD2En3CElAEJQ9bz1q0bmZIhlc
          type: text
      body:
        mode: raw
        raw: "[\r\n    {\r\n        \"name\":\"Evo X\"\r\n    },\r\n    {\r\n        \"name\":\"Lancer\"\r\n    }\r\n]"
        options:
          raw:
            language: json
      url:
        raw: http://localhost:8080/publishers/all
        protocol: http
        host:
          - localhost
        port: '8080'
        path:
          - publishers
          - all
    response: []
  - name: updatePublisher
    request:
      method: PUT
      header:
        - key: Authorization
          value: >-
            eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBbGV4QGNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYzODY5NzIyMywiZXhwIjoxNjM4NzYyNzU5fQ.4uQv2NHCZldbzpy_7zD2En3CElAEJQ9bz1q0bmZIhlc
          type: text
      body:
        mode: raw
        raw: "{\r\n    \"id\": 1,\r\n    \"name\": \"Updated Publisher\"\r\n}"
        options:
          raw:
            language: json
      url:
        raw: http://localhost:8080/publishers/
        protocol: http
        host:
          - localhost
        port: '8080'
        path:
          - publishers
          - ''
    response: []
  - name: deletePublisherById
    request:
      method: DELETE
      header:
        - key: Authorization
          value: >-
            eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBbGV4QGNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYzODY5NzIyMywiZXhwIjoxNjM4NzYyNzU5fQ.4uQv2NHCZldbzpy_7zD2En3CElAEJQ9bz1q0bmZIhlc
          type: text
      url:
        raw: http://localhost:8080/publishers/1
        protocol: http
        host:
          - localhost
        port: '8080'
        path:
          - publishers
          - '1'
    response: []
