info:
  _postman_id: 48128c69-e9af-4e08-b184-ee78047d355b
  name: bookStoreApp.authors
  schema: https://schema.getpostman.com/json/collection/v2.1.0/collection.json
item:
  - name: findAuthorById
    request:
      method: GET
      header:
        - key: Authorization
          value: >-
            eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBbGV4QGNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYzODY5NzIyMywiZXhwIjoxNjM4NzYyNzU5fQ.4uQv2NHCZldbzpy_7zD2En3CElAEJQ9bz1q0bmZIhlc
          type: text
      url:
        raw: http://localhost:8080/authors/1
        protocol: http
        host:
          - localhost
        port: '8080'
        path:
          - authors
          - '1'
    response: []
  - name: findAllAuthors
    request:
      method: GET
      header:
        - key: Authorization
          value: >-
            eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBbGV4QGNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYzODY5NzIyMywiZXhwIjoxNjM4NzYyNzU5fQ.4uQv2NHCZldbzpy_7zD2En3CElAEJQ9bz1q0bmZIhlc
          type: text
      url:
        raw: http://localhost:8080/authors/all
        protocol: http
        host:
          - localhost
        port: '8080'
        path:
          - authors
          - all
    response: []
  - name: createAuthor
    request:
      method: POST
      header:
        - key: Authorization
          value: >-
            eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBbGV4QGNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYzODY5NzIyMywiZXhwIjoxNjM4NzYyNzU5fQ.4uQv2NHCZldbzpy_7zD2En3CElAEJQ9bz1q0bmZIhlc
          type: text
      body:
        mode: raw
        raw: "{\r\n    \"name\": \"Lock Tex\"\r\n}"
        options:
          raw:
            language: json
      url:
        raw: http://localhost:8080/authors/
        protocol: http
        host:
          - localhost
        port: '8080'
        path:
          - authors
          - ''
    response: []
  - name: createAllAuthors
    request:
      method: POST
      header:
        - key: Authorization
          value: >-
            eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBbGV4QGNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYzODY5NzIyMywiZXhwIjoxNjM4NzYyNzU5fQ.4uQv2NHCZldbzpy_7zD2En3CElAEJQ9bz1q0bmZIhlc
          type: text
      body:
        mode: raw
        raw: "[\r\n    {\r\n        \"name\": \"New World\"\r\n    },\r\n    {\r\n        \"name\": \"Lee Seen\"\r\n    }\r\n]\r\n"
        options:
          raw:
            language: json
      url:
        raw: http://localhost:8080/authors/all
        protocol: http
        host:
          - localhost
        port: '8080'
        path:
          - authors
          - all
    response: []
  - name: updateAuthor
    request:
      method: PUT
      header:
        - key: Authorization
          value: >-
            eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBbGV4QGNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYzODY5NzIyMywiZXhwIjoxNjM4NzYyNzU5fQ.4uQv2NHCZldbzpy_7zD2En3CElAEJQ9bz1q0bmZIhlc
          type: text
      body:
        mode: raw
        raw: "{\r\n    \"id\": 1,\r\n    \"name\": \"Updated Author\"\r\n}"
        options:
          raw:
            language: json
      url:
        raw: http://localhost:8080/authors/
        protocol: http
        host:
          - localhost
        port: '8080'
        path:
          - authors
          - ''
    response: []
  - name: deleteAuthorById
    request:
      method: DELETE
      header:
        - key: Authorization
          value: >-
            eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBbGV4QGNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYzODY5NzIyMywiZXhwIjoxNjM4NzYyNzU5fQ.4uQv2NHCZldbzpy_7zD2En3CElAEJQ9bz1q0bmZIhlc
          type: text
      body:
        mode: raw
        raw: ''
        options:
          raw:
            language: json
      url:
        raw: http://localhost:8080/authors/1
        protocol: http
        host:
          - localhost
        port: '8080'
        path:
          - authors
          - '1'
    response: []
